<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px" />

# Numpy Ladder Challenge - Notebook 2

_Author:_ Tim Book

# Climb the Ladder!
Our class moves quickly! Sometimes, it feels like we make leaps in logic that are a bit too big. In this ladder challenge, we'll learn some core math concepts, some linear algebra, and the `numpy` library. Problems in this notebook start out easy and progressively get harder, so that the next rung of the Python ladder is always within reach.

Additionally, since not all of the topics discussed in this ladder challenge are explicitly taught in our course, these problems come with many more hints, tips, suggestions, and even sometimes a mini-lesson. You are encouraged to Google frequently throughout the lesson. In many ways, this ladder is meant to be a challenge as well as educational in its own right.

**Remember our one rule: NO LOOPS! None of the exercises in this notebook require a loop. If you use a loop to solve any of these problems, you are solving the problem incorrectly.**

0) Import numpy in the usual way

In [1]:
import numpy as np

# Section III - Simulation
In the next section, we'll use functions within the `np.random` submodule. You can find documentation [here](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html).

27) Generate 10,000 random numbers between 0 and 1 and assign them to a variable. To verify you've simulated the data properly, make sure the mean is approximately 0.5.

In [2]:
r = np.random.random(10_000)

In [3]:
r.shape

(10000,)

28) What proportion of these numbers is below 0.1?

In [4]:
(r < 0.1).sum() / r.shape

array([0.1005])

29) What proportion of these numbers is above 0.8?

In [5]:
(r >= 0.8).sum() / r.shape

array([0.2062])

30) What proportion of these numbers is above 0.2 but below 0.3?

In [6]:
((r >= 0.2) & (r <= 0.3)).sum() / r.shape

array([0.1019])

31) Generate 10,000 random numbers between 2 and 4. To verify you've simulated the data properly, find the mean and make sure it is approximately what you expect.

* _Hint:_ There is no `numpy` function for this specifically. How can you use the function you just used to generate this?

In [7]:
r_2_4 = (np.random.random(10_000) *2) + 2

32) What proportion of these numbers is between 2.4 and 2.6?

In [8]:
((2.6 >= r_2_4) & (r_2_4 >= 2.4)).sum() / r_2_4.shape

array([0.0978])

33) Generate 100,000 random standard normal (i.e., mean 0 standard deviation 1) numbers. Again, find the mean to verify you've done this properly.

In [9]:
n = np.random.standard_normal(100_000)

In [10]:
n

array([-0.21450203, -0.50691056,  1.22842789, ..., -0.48784997,
        0.30269393,  1.11778346])

In [11]:
n.mean()

0.0029317437427338706

34) What proportion of these numbers is negative?

In [12]:
(n < 0).sum() / n.shape

array([0.49693])

35a) What proportion of these numbers is between -1 and 1?

In [13]:
((n > -1) & (n < 1)).sum() / n.shape

array([0.68161])

35b) What proportion of these numbers is between -2 and 2?

In [14]:
((n > -2) & (n < 2)).sum() / n.shape

array([0.95496])

35c) What proportion of these numbers is between -3 and 3? Have you seen your last 3 solutions before? (If you've taken an intro stats course in college before, you will have.)

In [15]:
((n > -3) & (n < 3)).sum() / n.shape

array([0.99701])

### For the next few problems, we will be playing Rock-Paper-Scissors
If you are unfamiliar with the game Rock-Paper-Scissors, it features two combatants choosing one of three hand motions: rock, paper, or scissors. Rock beats scissors, scissors beats paper, and paper beats rock. Two friends are playing: Karen and Tom. Unbeknownst to them, you've been studying and recording both of their play patterns. Karen chooses rock 40% of the time, paper 10% of the time, and scissors 50% of the time. For Tom, it's rock 10%, paper 60%, scissors 30%. Who wins the most often?

**This is an extremely difficult question.** We will get to the answer in a few guided steps. You'll want to use `np.random.choice()` to help you through this.

36) Create vectors `p_karen` and `p_tom` that represent their respective probabilities for rock, paper, and scissors.

In [16]:
# r, p, s
p_karen = [.4, .1, .5]
p_tom = [.1, .6, .3]

37) Simulate 5 games. Who wins the majority of them? Just eyeball this one. (No one wins a draw.)

In [17]:
['Draw' if i == j else {'Karen': (i,j)} if i > j else {'Tom':(i,j)} for i,j in list(zip(np.random.choice(p_karen, 5), np.random.choice(p_tom,5)))]

[{'Tom': (0.5, 0.6)},
 {'Karen': (0.4, 0.3)},
 {'Tom': (0.5, 0.6)},
 'Draw',
 {'Tom': (0.1, 0.3)}]

38) Let's write a function to handle _one game at a time_. Write a function called `rps` that takes two arguments: `karen` and `tom` that will be either `"R"`, `"P"`, or `"S"`. The function will return `"K"`, `"T"`, or `"D"`, representing Karen, Tom, or a draw. That is, the function should give the following results:

* `rps("R", "P") ==> "T"`
* `rps("R", "S") ==> "K"`
* `rps("R", "R") ==> "D"`


* _Hint:_ Your answer will be a mess of `if`/`elif` statements.

In [18]:
def rps(karen,tom):
    d_karen = dict(R=.4, P= .1,S=.5)
    d_tom = dict(R=.1, P=.6, S=.3)
    return 'Draw' if d_karen.get(karen) == d_tom.get(tom) else 'Karen' if d_karen.get(karen) > d_tom.get(tom) else 'Tom'

In [19]:
[rps("R", "P"),
rps("R", "S"),
rps("R", "R"),]

['Tom', 'Karen', 'Karen']

39) As it stands now, the function you have written cannot handle vector data. Luckily, `numpy` gives us a function that allows us to vectorize any function we want. Use `np.vectorize` to create `rps_vectorized`, the vectorized version of `rps`. Skim the docs [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html).

In [20]:
rps_vectorized = np.vectorize(rps)

40) Simulate 1,000,000 (yes, one million) games. How often does Karen win? You can find the results by:

1. Replicating your solution to problems 37 and 38, except for one million instead of 5.
1. Using the function you made in problem 39.


* _Note 1:_ These probabilities are relatively difficult to figure out by hand. Some probabilities are best discovered by simulation. Another way of asking the above question is "What is the probability of Karen winning?")
* _Note 2:_ Look what we did! We used vectorization to completely eliminate the need for a loop! You _could_ have solved this problem with a loop, but it would have taken significantly more computer time.

In [21]:
# my CPU cannot physically compute 1 million simulations. I will need to do it in batches or i will try a CuPy implementation

In [22]:
output = rps_vectorized(np.random.choice(['R','P','S'],100_000),np.random.choice(['R','P','S'],100_000))

In [23]:
(output == 'Karen').sum() / 100_000

0.44726

In [24]:
# with only 100,000 simulations, Karen wins around 44 %of the time

In [25]:
# Below was an attempt at an implementation with the GPU, i'm moving on 

### Regression Simulation
Next, suppose we're trying to simulate some fake data for a regression problem we wish to give to our students. We wish to simulate data for the following equation:

$$y = 1000 + 200x + \varepsilon$$

Where $\varepsilon \sim N(0, 20)$ (that is, $\varepsilon$ is normally distributed with mean 0 and standard deviation 20).

41) Generate 10 $x$s from the $N(50, 10)$ distribution. (That is, the normal distribution with mean 50 and standard deviation 10).

In [30]:
x = np.random.normal(50,10,10)
x

array([61.06460556, 48.19936526, 65.37388762, 31.58704032, 59.82404242,
       46.90265125, 37.4720084 , 45.41134116, 61.68874562, 56.98133659])

42) Generate 10 $\varepsilon$s from the appropriate distribution described above.

In [31]:
e = np.random.normal(0,20,10)
e

array([ 17.29628574, -21.68385105, -14.74903604,  26.00767625,
        10.49161667,   8.13049243,  13.92511805, -18.08139914,
        11.19182776, -24.2290605 ])

43) Simulate the $y$s as described above using the two vectors you made in the previous two problems.

In [32]:
y = 1000 + (200 * x) + e
y

array([13230.21739692, 10618.18920132, 14060.02848706,  7343.41574015,
       12975.30010008, 10388.6607418 ,  8508.32679751, 10064.18683363,
       13348.94095212, 12372.03825736])

# Section IV: Matrices
_Tiny note:_ In general, we have told you it's against Python's style guide to use capital letters when defining variables. The one exception we make is when our variables represent mathematical objects. So feel free to name the following variables things like `A`, `B`, etc.!

44) Create the following matrix:

$$
A =
\begin{bmatrix}
3 & -1 & 5 \\
-2 & 0 & 8 \\
4 & 5 & -7
\end{bmatrix}
$$

In [33]:
A = np.matrix('3 -1 5; -2 0 8; 4 5 -7')
A

matrix([[ 3, -1,  5],
        [-2,  0,  8],
        [ 4,  5, -7]])

45) Create the following matrix:

$$
B =
\begin{bmatrix}
-3 & 8 & 2 \\
2 & -3 & 5 \\
0 & 6 & -2
\end{bmatrix}
$$

In [36]:
B = np.matrix('-3 8 2; 2 -3 5; 0 6 -2')
B

matrix([[-3,  8,  2],
        [ 2, -3,  5],
        [ 0,  6, -2]])

In [38]:
B1 = np.asarray([
    [-3, 8, 2],
    [2, -3, 5],
    [0, 6, 2]
])
B1

array([[-3,  8,  2],
       [ 2, -3,  5],
       [ 0,  6,  2]])

In [39]:
B2 = np.array([
    [-3, 8, 2],
    [2, -3, 5],
    [0, 6, 2]
])
B2

array([[-3,  8,  2],
       [ 2, -3,  5],
       [ 0,  6,  2]])

46) Use `np.eye()` to create the following matrix:

$$
I = I_3 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$$

In [40]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# i miss you identity matrix !

47) Triple every element of `B`. (Do not reassign.)

In [43]:
B * 3

matrix([[-9, 24,  6],
        [ 6, -9, 15],
        [ 0, 18, -6]])

48) Index `A` in order to get me -7.

In [61]:
A

matrix([[ 3, -1,  5],
        [-2,  0,  8],
        [ 4,  5, -7]])

In [51]:
A.item(2,2)

-7

In [56]:
A[(2,2)]

-7

In [57]:
A[2,2]

-7

49) Index `A` in order to get me 0.

In [60]:
A

matrix([[ 3, -1,  5],
        [-2,  0,  8],
        [ 4,  5, -7]])

In [62]:
A[1,1]

0

50) Index `A` to get me $\begin{bmatrix} -2 & 0 & 8 \end{bmatrix}$

In [63]:
A[1]

matrix([[-2,  0,  8]])

51) Index `A` to get me
$$
\begin{bmatrix}
-1 \\ 0 \\ 5
\end{bmatrix}
$$

(You can ignore the fact that it may print out as a row vector)

In [66]:
# https://stackoverflow.com/questions/4455076/how-to-access-the-ith-column-of-a-numpy-multidimensional-array
A[:,1]

matrix([[-1],
        [ 0],
        [ 5]])

52) Index `A` to get me
$$
\begin{bmatrix}
0 & 8 \\
5 & -7 
\end{bmatrix}
$$

In [67]:
A[1:,1:]

matrix([[ 0,  8],
        [ 5, -7]])

53) Redefine the middle column of `A` to be
$$
\begin{bmatrix}
-2 \\ 1 \\ 7
\end{bmatrix}
$$

In [72]:
A[:,1] = [[-2],
         [1],
         [7]]

In [73]:
A

matrix([[ 3, -2,  5],
        [-2,  1,  8],
        [ 4,  7, -7]])

54) Index `B` to define the following matrix:
$$
C = 
\begin{bmatrix}
8 & 2 \\
-3 & 5 \\
6 & -2
\end{bmatrix}
$$

In [74]:
B

matrix([[-3,  8,  2],
        [ 2, -3,  5],
        [ 0,  6, -2]])

In [114]:
C = B[:,1:]
C

matrix([[ 8,  2],
        [-3,  5],
        [ 6, -2]])

55) What is $A + B$?

In [83]:
A + B

matrix([[ 0,  6,  7],
        [ 0, -2, 13],
        [ 4, 13, -9]])

56) What is $2A - 3B$?

In [84]:
(2 * A) - (3 * B)

matrix([[ 15, -28,   4],
        [-10,  11,   1],
        [  8,  -4,  -8]])

57) What is the elementwise product of $A$ and $B$?

In [88]:
np.multiply(A,B)

matrix([[ -9, -16,  10],
        [ -4,  -3,  40],
        [  0,  42,  14]])

58) What is $AB$?

In [89]:
A * B

matrix([[-13,  60, -14],
        [  8,  29, -15],
        [  2, -31,  57]])

59) What is $BA$? And why isn't it the same as $AB$?

In [90]:
B * A

matrix([[-17,  28,  35],
        [ 32,  28, -49],
        [-20,  -8,  62]])

In [91]:
# Row Multiplication

In [103]:
A, B

(matrix([[ 3, -2,  5],
         [-2,  1,  8],
         [ 4,  7, -7]]),
 matrix([[-3,  8,  2],
         [ 2, -3,  5],
         [ 0,  6, -2]]))

In [104]:
A[0,:], B[:,0]

(matrix([[ 3, -2,  5]]),
 matrix([[-3],
         [ 2],
         [ 0]]))

In [106]:
(3 * -3) + (-2 * 2) + (5 * 0)

-13

In [111]:
(A*B)[0,0]

-13

In [105]:
B[0,:], A[:,0]

(matrix([[-3,  8,  2]]),
 matrix([[ 3],
         [-2],
         [ 4]]))

In [107]:
(-3 * 3) + (8 * -2) + (2* 4)

-17

In [112]:
(B*A)[0,0]

-17

60) What is $AI$, and is it equal to $IA$? Does this product look familiar?

In [ ]:
# A * I should equal A
# I * A should equal A

In [ ]:
# This is the product of the identity matrix

61) What is $AC$?

In [115]:
A * C

matrix([[ 60, -14],
        [ 29, -15],
        [-31,  57]])

62) Why do we get an error when calculating $CA$?

In [124]:
try:
    C * A
except:
    print(f'Matrix Dimensions must agree. {C.shape} and {A.shape} do not agree' )

Matrix Dimensions must agree. (3, 2) and (3, 3) do not agree


In [117]:
# You need to multiply matricies that fit the inside rule
# For a Matrix (m*n) and another matrix (o*p)
# n == o
# else, matrix dimensions must agree 
#MATLAB

63) What is $A^TA$? Note that you answer will be a _diagonal matrix_, that is, a matrix that is equal to its transpose.

In [132]:
A

matrix([[ 3, -2,  5],
        [-2,  1,  8],
        [ 4,  7, -7]])

In [133]:
A.transpose() * A

matrix([[ 29,  20, -29],
        [ 20,  54, -51],
        [-29, -51, 138]])

64) What is $A^TB$?

In [134]:
A.transpose() * B

matrix([[-13,  54, -12],
        [  8,  23, -13],
        [  1, -26,  64]])

65) What is $A^{-1}$ (the inverse of $A$).

In [137]:
np.linalg.inv(A)

matrix([[ 0.2       , -0.06666667,  0.06666667],
        [-0.05714286,  0.13015873,  0.10793651],
        [ 0.05714286,  0.09206349,  0.0031746 ]])

66) What is $AA^{-1}$? Does it look familiar?

* _Hint:_ Maybe call an `np.round()` on your result.

In [141]:
np.round(A * np.linalg.inv(A))

matrix([[ 1.,  0., -0.],
        [ 0.,  1.,  0.],
        [-0., -0.,  1.]])

In [ ]:
# Our Identity matrix is back!

67) What is $(B + A^TA)^{-1}A^TC$?

In [142]:
np.linalg.inv((B + A.transpose() * A)) * A.transpose() * C

matrix([[ 3.00215282, -0.28385833],
        [-0.62588766,  0.33839645],
        [ 0.24189329,  0.52202903]])

In [143]:
# Order matters when dealing with matrix operations !